### PR TITLE
Skip XQJ SWIG bindings if no Zorba API JAR

### PR DESCRIPTION
**Pull request by alyst**
XQJ JAR is dependent on zorba_api.jar, so XQJ Jar generation needs to be skipped if zorba_api.jar is not found.
Actually, this issue gets exposed because CMakeLists.txt for zorba_api.jar and XQJ jar check for Java in different ways: the former looks for java include path, while the latter searches for javac executable. On my system these checks give different results.

### CODE REVIEW

**Comment by wcandillon** [comment]
@fcavalieri It looks good to me. Do you approve it?

**Comment by fcavalieri** [comment]
@wcandillon I am on it.

**Comment by wcandillon** [comment]
@fcavalieri any news on this?

**Comment by fcavalieri** [comment]
Deprecated by #165

**Pull request closed without merging**
