### PR TITLE
circleci integration

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
@fcavalieri Could you look at the circleci log? There seems to be something specific to circleci environnement. Not sure why I'm getting these errors.

**Comment by wcandillon** [comment]
@fcavalieri this is not ready for review yet but it does compile zorba and run the tests across 8 cores.

**Comment by fcavalieri** [comment]
@wcandillon The only failing test remain is a bug in zorba. Something in
PHP5.5 made this bug appear. I added this to my todo.

**Comment by wcandillon** [comment]
@fcavalieri there are some other minor touch ups I need to do (external modules, cleaning the template file etc).

**Pull request closed without merging**
